services:
  tools-server:
    build: .
    ports:
      - "3010:3000"
    volumes:
      - ./logs:/usr/src/server/logs
      - ./static:/usr/src/server/static
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /usr/src/server/google-credentials.json
    restart: unless-stopped
